name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qgis_version: [3.44-questing, 4.0-questing]

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: |
        docker run \
          -v $(pwd):/usr/src \
          -w /usr/src \
          qgis/qgis:${{ matrix.qgis_version }} \
          sh -c '
            PYVER=$(python3 -c "import sys; print(f\"{sys.version_info.major}.{sys.version_info.minor}\")")
            export PYTHONPATH=/usr/share/qgis/python:/usr/share/qgis/python/plugins:/usr/lib/python3/dist-packages:/usr/lib/python${PYVER}/dist-packages
            xvfb-run pytest-3
          '
