name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  pyqt6-check:
    uses: opengisch/qgis-plugin-ci/.github/workflows/pyqt6_test.yml@master
    with:
      plugin_path: document_management_system

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        docker run -v ${GITHUB_WORKSPACE}:/src -w /src opengisch/qgis:stable sh -c 'xvfb-run pytest-3'
      env:
        DOCKER_IMAGE: ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }}
